# We're going to try some fundamentals

more specifically, we're going to cover:
* intro to tensors
* getting info from tensors
* manipulating tensors
* Tensors & NumPy
* using @tf.function (method to speed up python funtions)
* Using GPU's with Tensorflow  
* Exercises for yourself
# New Section


#Introduction to Tensors 

In [1]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [2]:
# create tensors with tf.constant()

scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
#check number of dimension of a tensor
scalar.ndim

0

In [4]:
# create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# check dimension of vector
vector.ndim

1

In [6]:
# create a matrix, matrix = more than 1 dimension 
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
matrix.ndim

2

In [8]:
# create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# what is the number of dimensions of another matrix
another_matrix.ndim

2

In [10]:
# create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6,]],
                      
                       [[7, 8, 9,],
                       [10, 11, 12,]],
                      
                       [[13, 14,15],
                       [16, 17, 18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim

3

# What we've created so far
- scaler = a single number
- vector = a number with direction, e.g. wind speed and direction 
- matrix = two dimensional array of numbers
- tensor = an n-dimensional array of numbers  (where N can be any number, 0 = scaler, 1 dimension = vector)

# Create tensor with tf.Variable

In [12]:
# Create the same tensor with tf.Variable() as above 

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's try to change one of the elements in our changable tensor

#changeable_tensor[0] = 7
#changeable_tensor

In [14]:
# How about we try .assign()

changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [15]:
# Let's try to change our unchangable tensor
#unchangeable_tensor[0].assign(7)
#unchangeable_tensor



# Creating Random Tensors 

Random Tensors are Tensors of some arbitary size that contains random numbers.



In [16]:
# create two random tensors (but the same) with code

random_1 = tf.random.Generator.from_seed(42) # set a seed for reproducibility 
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # the seed loads the random number = psuedo random
random_2 = random_2.normal(shape=(3,2))

# are they equal ? 
random_1, random_2, random_1 == random_2 # output the random numbers, and then compare



(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor 


In [17]:
# shuffle a tensor  (valuable for when you want to shuffle your data, so that inherent order doesn't affect the model)

not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])

not_shuffled.ndim

2

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [19]:
# shuffle out non_shuffled Tensor
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [20]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

# home work 

**Read** tensorFlow documentation on random seed generation: 
https://tensorflow.org/api_docs/python/tf/random/set_seed and then practice writing 5 random tensors and shuffle them 

**reading documentation** is hard at first, but keep reading, it will make more sense. 

**What did we learn?** 

it looks like if we shuffle tensors to be in the same order, we have to use the global level random seed as well as the operational level seed

> **rule 4** If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [21]:
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'
print(tf.random.uniform([1]))  # generates 'A3'
print(tf.random.uniform([1]))  # generates 'A4'

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)
tf.Tensor([0.7402308], shape=(1,), dtype=float32)


In [22]:
tf.random.set_seed(1234)
print(tf.random.uniform([1]))  # generates 'A1'
print(tf.random.uniform([1]))  # generates 'A2'

tf.Tensor([0.5380393], shape=(1,), dtype=float32)
tf.Tensor([0.3253647], shape=(1,), dtype=float32)


In [23]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)


In [24]:
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'
tf.random.set_seed(1234)
print(tf.random.uniform([1], seed=1))  # generates 'A1'
print(tf.random.uniform([1], seed=1))  # generates 'A2'

tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)
tf.Tensor([0.1689806], shape=(1,), dtype=float32)
tf.Tensor([0.7539084], shape=(1,), dtype=float32)


In [25]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.6087816], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.7539084], dtype=float32)>)


In [26]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.4.1


In [27]:
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])

not_shuffled.ndim

tf.random.shuffle(not_shuffled, seed=42)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [28]:

not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])

not_shuffled.ndim

tf.random.set_seed(42) #global seed
tf.random.shuffle(not_shuffled, seed=42) # operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

Basically, the reason we care about this, is that we want random, but we want to reproduce the same output each time, so we randomise the input, using a seed, that seed ensures that the same randomisation occurs each time we run the code: 

**sequence is deterministic**

# Creating Tensors from NumPy arrays



In [29]:
tf.ones([10, 7])


<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [30]:
tf.zeros([3, 4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into Tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on GPU's for much faster computing

In [31]:
# you can also turn NumPy arrays into TensorFlow Tensors 

import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a numpy array between 1 and 25
numpy_A 

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [32]:
# if you look abovem output = array

A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [33]:
# if you look above, output is now a tensor 

2 * 3 * 4

24

In [34]:
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A)
A, B 

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

### Getting information from tensors

When dealing with Tensors, you probably want to be aware fo the following: 

* Shape
* Rank
* Axis or Dimension
* Size

These are some of the main tensor attributes



In [35]:
# create a rank 4 tensor (4 dimensions)

rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [36]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [37]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [38]:
# Get various attributes of our tensor 

print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shae of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("The total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shae of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
The total number of elements in our tensor: 120


### Indexing Tensors

Tensors can be indexed just like Python Lists.

In [39]:
# example of using python to index a list

some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [40]:
# get the first 2 elements of each dimension 

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [41]:
# get the first element from each dimension from each index, except for the final one

some_list[:1] # example in python

rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [42]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [43]:
# looking for the first on each element except the 3rd element?? 

rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [44]:
# create a rank 2 tensor (2 dimensions)

rank_2_tensor = tf.constant([[10, 7],
                            [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim, 

(TensorShape([2, 2]), 2)

In [45]:
# Get various attributes of our tensor 

print("Datatype of every element:", rank_2_tensor.dtype)
print("Number of dimensions (rank):", rank_2_tensor.ndim)
print("Shae of tensor:", rank_2_tensor.shape)
print("Elements along the 0 axis:", rank_2_tensor.shape[0])
print("Elements along the last axis:", rank_2_tensor.shape[-1])
print("The total number of elements in our tensor:", tf.size(rank_2_tensor).numpy())

Datatype of every element: <dtype: 'int32'>
Number of dimensions (rank): 2
Shae of tensor: (2, 2)
Elements along the 0 axis: 2
Elements along the last axis: 2
The total number of elements in our tensor: 4


In [46]:
# get the last item of each row of our rank_2_tensor

rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [47]:
# Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis] #these 3 dots means on every previous axis of this one
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [48]:
# Alternative to tf.newaxis

tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [49]:
# Expand 0 axis 

tf.expand_dims(rank_2_tensor, axis=0) # expand the zero axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (Tensor Operations) - vid 16 [2.15 ish]

**Basic Operations**

`+`, `-`, `*`, `/`

In [50]:
# you can add a value to a tensor using the addition operator 

tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [51]:
# original tensor is unchanged 
# this is important because we may not want to change the tensor 

tensor 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [52]:
# above example shows the addition of 10 to the tensor, but running the code in another cell, merely calling the constant without the operator reverts to original tensor values 
# 10, 7 + 10 created 20, 17 in first cell, but in next cell, we revert back to constant which produces 10, 7 etc

# this works for subtraction and other operators as well. 

# we can use the tensor flow built in function too

tf.multiply(tensor, 10) # tf.math.mulltiply 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [53]:
# the reason we would use the TensorFlow functions is because they will run faster on GPU's

**Matrix Multiplication**

in machine learning, matric multiplication is one of the most common tensor operations

- looking back, the examples we were doing before are called element wise

**Element wise** is basically where you multiple each number seperately, i.e. [10, 7] `*` 10 becomes [10 * 10] and [10 * 7] 

Multiplying a Matrix by a Matrix (Matrix = Tensor) is a little more complicated. 

Good website to look at is http://matrixmultiplication.xyz 


There are two rules our tensors or matrices need to fulfil if we are going to matrix multiply them: 

1. the inner dimensions must match
2. the resulting matrix has the shape of the outer dimension 



In [54]:
# matrix multiplication in tensorflow 

print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

### practice using some tensor multiplication

input numbers: 
A [1, 2, 5]
  [7, 2, 1]
  [3, 3, 3,] 

B [3, 5] 
  [6, 7]
  [1, 8]

Answer should be: 

C [20, 59]
  [34, 57]
  [30, 60] 

We can try using tensor multiplication as follows: 

In [55]:
tensor_A = tf.constant([[[1, 2, 5],
                         [7, 2, 1],
                         [3, 3, 3]]])

tensor_B = tf.constant([[[3, 5],
                         [6, 7],
                         [1, 8]]])

tensor_C = tf.matmul(tensor_A, tensor_B)

tensor_A, tensor_B, tensor_C

(<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
 array([[[1, 2, 5],
         [7, 2, 1],
         [3, 3, 3]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
 array([[[3, 5],
         [6, 7],
         [1, 8]]], dtype=int32)>,
 <tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
 array([[[20, 59],
         [34, 57],
         [30, 60]]], dtype=int32)>)

In [56]:
# we could try using the Matrix Multiplication with the Python Operator "@" as well

tensor_D = tensor_A @ tensor_B
tensor_D

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[20, 59],
        [34, 57],
        [30, 60]]], dtype=int32)>

In [57]:
print("Tensor A")
print("Number of dimensions (rank):", tensor_A.ndim)
print("Shae of tensor:", tensor_A.shape)
print("Elements along the 0 axis:", tensor_A.shape[0])
print("Elements along the last axis:", tensor_A.shape[-1])
print("The total number of elements in our tensor:", tf.size(tensor_A).numpy())
print("Tensor B")
print("Number of dimensions (rank):", tensor_B.ndim)
print("Shae of tensor:", tensor_B.shape)
print("Elements along the 0 axis:", tensor_B.shape[0])
print("Elements along the last axis:", tensor_B.shape[-1])
print("The total number of elements in our tensor:", tf.size(tensor_B).numpy())
print("Tensor C")
print("Number of dimensions (rank):", tensor_C.ndim)
print("Shae of tensor:", tensor_C.shape)
print("Elements along the 0 axis:", tensor_C.shape[0])
print("Elements along the last axis:", tensor_C.shape[-1])
print("The total number of elements in our tensor:", tf.size(tensor_C).numpy())
print("Tensor D")
print("Number of dimensions (rank):", tensor_D.ndim)
print("Shae of tensor:", tensor_D.shape)
print("Elements along the 0 axis:", tensor_D.shape[0])
print("Elements along the last axis:", tensor_D.shape[-1])
print("The total number of elements in our tensor:", tf.size(tensor_D).numpy())

Tensor A
Number of dimensions (rank): 3
Shae of tensor: (1, 3, 3)
Elements along the 0 axis: 1
Elements along the last axis: 3
The total number of elements in our tensor: 9
Tensor B
Number of dimensions (rank): 3
Shae of tensor: (1, 3, 2)
Elements along the 0 axis: 1
Elements along the last axis: 2
The total number of elements in our tensor: 6
Tensor C
Number of dimensions (rank): 3
Shae of tensor: (1, 3, 2)
Elements along the 0 axis: 1
Elements along the last axis: 2
The total number of elements in our tensor: 6
Tensor D
Number of dimensions (rank): 3
Shae of tensor: (1, 3, 2)
Elements along the 0 axis: 1
Elements along the last axis: 2
The total number of elements in our tensor: 6


There are two rules our tensors or matrices need to fulfil if we are going to matrix multiply them: 

1. the inner dimensions must match
2. the resulting matrix has the shape of the outer dimension 

following, I have broken the Matrix, E has a shape 1,3,3 but F has a shape 1, 2, 2 - which will fail at runtime, 

```
tensor_E = tf.constant([[[1, 1],
                         [3, 4],
                         [5, 6]]])

tensor_F = tf.constant([[[7, 8],
                         [9, 10],
                         [11, 12]]])
```

in order to solve this I believe we need to add an axis as follows: 

``` 
tf.expand_dims(tensor_F, axis=0) 
```

In [58]:
tensor_E = tf.constant([[1, 1],
                         [3, 4],
                         [5, 6]])

tensor_F = tf.constant([[7, 8],
                         [9, 10],
                         [11, 12]])

# seems we can simply reshape the tensor... 
tf.reshape(tensor_F, shape=(2, 3))

# tensor_G = tf.matmul(tensor_E, tensor_F) 

tensor_E, tensor_F, # tensor_G 

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 1],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

## GOING BACK TO MULTIPLICATION - RESUME VIDEO at 2.32.16 (vid 17)

In [59]:
X = tf.constant([[1, 2],
                  [3, 4],
                  [5, 6]])

Y = tf.constant([[7, 8],
                  [9, 10],
                  [11, 12]])

X, Y

# tf.matmul(X, Y)
# this will fail = InvalidArgumentError: In[0] mismatch In[1] shape: 2 vs. 3: [1,3,2] [1,3,2] 0 0 [Op:BatchMatMulV2]
# instead we need to reshape one of the tensors

# let's change the shape of Y
tf.reshape(Y, shape=(2, 3))

# we can look for more information by using the following shape output: 

X.shape, tf.reshape(Y, shape=(2,3)).shape

(TensorShape([3, 2]), TensorShape([2, 3]))

In [60]:
# try to perform matrix multiply X by reshaped Y

X @ tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [61]:
# try to use tf.matmul

tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [62]:
# if we are to reverse this, reshaping X instead of Y, would that work? 
# if in doubt, code it out!! 

# first try the matrix multiply @ operation 

Y @ tf.reshape(X, shape=(2, 3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [63]:
# we can see the output is different, but we will try matmul as well: 

tf.matmul(Y, tf.reshape(X, shape=(2, 3)))


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 39,  54,  69],
       [ 49,  68,  87],
       [ 59,  82, 105]], dtype=int32)>

In [64]:
# again the output matches the previous operation (Y by a reshaped X, but the output is not the same as an X by reshaped Y)

# can we do the same with transpose? 

X, tf.transpose(X), tf.reshape(X, shape=(2, 3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

the output is completely different: 

```
 (<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)
```



**The Dot Product**

Matrix multiplication is also referred to as the dot product

You can perform matrix multipleication using: 

* `tf.matmul()`
* `tf.tensordot()`
* `@`


In [65]:
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [66]:
# Perform the dot product on X and Y (requires X or Y to be transposed)

# transposing is 'flipping the axis' whereas re-shaping is 'reshuffling' 

tf.tensordot(tf.transpose(X), Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [67]:
# perform matrix multiplication between X and Y (transposed)

tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [68]:
# perform matrix multiplication between X and Y (reshaped)

tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [69]:
# Check the vlaues of Y reshape Y, Transposed Y

print("Normal Y:")
print(Y, "\n") 

print("Reshaped Y:")
print(tf.reshape(Y, shape=(2, 3)), "\n") 

print("Transposed Y to (2, 3):")
print(tf.transpose(Y), "\n") 




Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Reshaped Y:
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y to (2, 3):
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



Generally when performing Matrix Multiplications on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors to satisfy the matrix multiplication rules  

### Changing the Data Type (datatype) of a tensor 

*Video 20 -> 2.59.29*

most tensors will be Int32 

In [70]:
# create a new tensor with default datatype (float32) --- we did just say most are integers right..... 

B = tf.constant([1.7, 7.4])
C = tf.constant([7, 10])
B.dtype, C.dtype

(tf.float32, tf.int32)

In [71]:
# what you can see here is the datatype automatically matches the data provided to it

### change from Float32 to Float16 /// this is called reduced precision 

Mixed precision is the use of both 16-bit and 32-bit floating-point types in a model during training to make it run faster and use less memory.

Today, most models use the float32 dtype, which takes 32 bits of memory. However, there are two lower-precision dtypes, float16 and bfloat16, each which take 16 bits of memory instead. Modern accelerators can run operations faster in the 16-bit dtypes, as they have specialized hardware to run 16-bit computations and 16-bit dtypes can be read from memory faster.

In [72]:
# now we want to change from a float32 to a float16 datatype: 

D = tf.constant([1.7, 7.4])
# B2 = tf.constant([1.7, 7.4], dtype=tf.float16) # this was my attempt before watching video:
D = tf.cast(B, dtype=tf.float16)
D, # B2.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,)

In [73]:
# change from int32 to float32

E2 = tf.cast(C, dtype=tf.float32)
E2

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>

### aggrigating tensors 

Aggregating Tensors = condensing them from multiple values to smaller amount of values 

In [74]:
# get the absolute values (probably not best form of aggregation to start with)

D = tf.constant([-7, -10])
D

tf.abs(D) # this basically makes a negative number into a positive number?

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation: 

* get the minimum
* get the maximum
* get the MEAN of a tensor
* get the SUM of a tensor


In [75]:
# my testing before video resumes (Video 21 3.12.08) 

DD_mean = tf.constant([[[1, 2], 
                        [1, 3], 
                        [4, 21]]])

# tf.reduce_mean(DD_mean)

print("Initial Output Mean_DD:")
print(DD_mean, "\n") 
print("Mean of output Mean_DD:")
print(tf.reduce_mean(DD_mean), "\n") 
print("Maximum of output Mean_DD:")
print(tf.reduce_max(DD_mean), "\n") 
print("Minimum of output Mean_DD:")
print(tf.reduce_min(DD_mean), "\n") 
print("Sum of output Mean_DD:")
print(tf.reduce_sum(DD_mean), "\n") 

Initial Output Mean_DD:
tf.Tensor(
[[[ 1  2]
  [ 1  3]
  [ 4 21]]], shape=(1, 3, 2), dtype=int32) 

Mean of output Mean_DD:
tf.Tensor(5, shape=(), dtype=int32) 

Maximum of output Mean_DD:
tf.Tensor(21, shape=(), dtype=int32) 

Minimum of output Mean_DD:
tf.Tensor(1, shape=(), dtype=int32) 

Sum of output Mean_DD:
tf.Tensor(32, shape=(), dtype=int32) 



In [76]:
# create a random tensor to practice these reduce operations (0 and 100 of size 50)

F = tf.constant(np.random.randint(low=0, high=100, size=50,))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([44, 45, 62, 66, 56,  3, 81, 76, 97, 52, 16, 79, 24, 41, 86,  8, 40,
        0, 53, 51, 76, 77, 53, 93, 12, 35, 34, 27, 17, 61, 22, 64, 50, 96,
       57,  4, 33, 87, 50, 84, 53, 47, 91, 21, 87,  0, 28, 77, 90, 71])>

In [77]:
print("Datatype of every element:", F.dtype)
print("Number of dimensions (rank):", F.ndim)
print("Shape of tensor:", F.shape)
print("Elements along the 0 axis:", F.shape[0])
print("Elements along the last axis:", F.shape[-1])
print("The total number of elements in our tensor:", tf.size(F).numpy())

print("Initial Output:")
print(F) 
print("Mean of output:")
print(tf.reduce_mean(F)) 
print("Maximum of output:")
print(tf.reduce_max(F)) 
print("Minimum of output:")
print(tf.reduce_min(F)) 
print("Sum of output:")
print(tf.reduce_sum(F)) 

Datatype of every element: <dtype: 'int64'>
Number of dimensions (rank): 1
Shape of tensor: (50,)
Elements along the 0 axis: 50
Elements along the last axis: 50
The total number of elements in our tensor: 50
Initial Output:
tf.Tensor(
[44 45 62 66 56  3 81 76 97 52 16 79 24 41 86  8 40  0 53 51 76 77 53 93
 12 35 34 27 17 61 22 64 50 96 57  4 33 87 50 84 53 47 91 21 87  0 28 77
 90 71], shape=(50,), dtype=int64)
Mean of output:
tf.Tensor(51, shape=(), dtype=int64)
Maximum of output:
tf.Tensor(97, shape=(), dtype=int64)
Minimum of output:
tf.Tensor(0, shape=(), dtype=int64)
Sum of output:
tf.Tensor(2577, shape=(), dtype=int64)


# video resumes [ find the Variance and standard deviation ] // video 22 > 3.16.17

import tensorflow_probability as tfp

tfp.stats.variance(F)

In [78]:
# now to find the Variance and standard deviation: 
# seems we needed TF Probability (import TFP)

import tensorflow_probability as tfp

print("Initial Output:")
print(F, "\n") 
print("Variance of output:")
print(tfp.stats.variance(F), "\n")
# print(tf.nn.moments(F, axes=[0])) # this also works
print("Standard Deviation of output:")
print(tf.math.reduce_std(tf.cast(F, dtype=tf.float32))) # we need to convert the Int to a float



Initial Output:
tf.Tensor(
[44 45 62 66 56  3 81 76 97 52 16 79 24 41 86  8 40  0 53 51 76 77 53 93
 12 35 34 27 17 61 22 64 50 96 57  4 33 87 50 84 53 47 91 21 87  0 28 77
 90 71], shape=(50,), dtype=int64) 

Variance of output:
tf.Tensor(790, shape=(), dtype=int64) 

Standard Deviation of output:
tf.Tensor(28.116337, shape=(), dtype=float32)


In [79]:
# find the positional maximum and minimum of a Tensor >> I re-wrod this to:
# find the index position from output `F` that has the maximum / minimum values
# // video 23 // 3.25

# tf.math.argmax(F) # this actually returns the index that shows where the largest integer is (counting from position 0)
# tf.math.argmin(F) # this actually returns the index that shows where the largest integer is (counting from position 0)

tf.math.argmax(F), tf.math.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=8>,
 <tf.Tensor: shape=(), dtype=int64, numpy=17>)

In [80]:
# let's create a new tensor to try this on
# we also want to set a global seed to keep the data the same at each instance, for comparing notes 

tf.random.set_seed(42)
F2 = tf.random.uniform(shape=[50])
F2

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [81]:
# find the positional maximum and minimum

tf.math.argmax(F2), tf.math.argmin(F2)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [82]:
# Index on our largest value

F2[tf.argmax(F2)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [83]:
# Find the max value of F

tf.reduce_max(F2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [84]:
# check if they are equal 

F2[tf.argmax(F2)] == tf.reduce_max(F2)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [85]:
print("Initial Output for F2:")
print(F2, "\n") 
print("Minimum Index location of F2:")
print(tf.math.argmin(F2), "\n")
print("Minimum Index content of F2:")
print(F2[tf.argmin(F2)], "\n")
print("Maximum Index location of F2:")
print(tf.math.argmax(F2), "\n")
print("Maximum Index content of F2:")
print(F2[tf.argmax(F2)], "\n")

Initial Output for F2:
tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32) 

Minimum Index location of F2:
tf.Tensor(16, shape=(), dtype=int64) 

Minimum Index content of F2:
tf.Tensor(0.009463668, shape=(), dtype=float32) 

Maximum Index location of F2:
tf.Tensor(42, shape=(), dtype=int64) 

Maximum Index content of F2:
tf.Tensor(0.9671384, shape=(), dtype=float32) 



### Break at video 24 // 3.32.01

### Squeezing a tensor (removing all single dimensions)

In [86]:
# create a tensor
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [87]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [88]:
G_squeezed = tf.squeeze(G) # this removes unwanted dimensions?? 
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot Encoding

Each category (variable) is converted into a dummy variable which is a binary representation for that category

https://www.onemoredavid.com/machine-learning-data-engineering/data-scrubbing#h.7r3cxruyss2t


In [89]:
# create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, yellow, blue

# one hot encode our list: 
# tf.one_hot(some_list) # failed = NameError: name 'depth' is not defined
# I tried same operation with 'depth added' but this told me depth was not defined, so I defined it in the operation:
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [90]:
# specify custom values for one hot encoding (rarely used in real life)

tf.one_hot(some_list, depth=4, on_value=True, off_value=False) # could also be "SOME STRING HERE" for the on/off values

<tf.Tensor: shape=(4, 4), dtype=bool, numpy=
array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])>

### some common math opertaions to try: Squaring, Log, Square Root

In [91]:
# log example from the documentation: 
x = tf.constant([0, 0.5, 1, 5]) 
tf.math.log(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([      -inf, -0.6931472,  0.       ,  1.609438 ], dtype=float32)>

In [92]:
# try a log example against own data: 
tf.math.log(F2)


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([-0.40862694, -0.818695  , -1.0416201 , -0.7668313 , -3.3914328 ,
       -0.37881485, -0.3009464 , -0.13645622, -1.4857773 , -1.4997011 ,
       -1.1699319 , -0.32526514, -2.0159998 , -0.6013634 , -0.5540658 ,
       -0.10571227, -4.6602955 , -0.6515625 , -0.45484787, -1.612802  ,
       -0.31550223, -0.60543936, -2.229655  , -0.39051828, -0.41509688,
       -1.0878195 , -0.50846565, -1.5576724 , -0.15930389, -0.8195685 ,
       -0.05284442, -1.4374784 , -0.20850994, -0.641809  , -0.70459646,
       -1.5318823 , -0.1675673 , -0.13709877, -1.1764023 , -0.37570658,
       -1.4369967 , -0.2462551 , -0.03341366, -2.6779823 , -0.22472051,
       -0.4150805 , -0.5324727 , -1.8041341 , -0.30367282, -1.1377468 ],
      dtype=float32)>

In [93]:
# trying the square from documentation: 
F3 = tf.math.square(F2)
F3

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([4.4164279e-01, 1.9448698e-01, 1.2452606e-01, 2.1574403e-01,
       1.1330233e-03, 4.6877623e-01, 5.4777384e-01, 7.6115942e-01,
       5.1223613e-02, 4.9816839e-02, 9.6340768e-02, 5.2176905e-01,
       1.7738823e-02, 3.0037400e-01, 3.3017528e-01, 8.0943036e-01,
       8.9561006e-05, 2.7168143e-01, 4.0264672e-01, 3.9731771e-02,
       5.3205711e-01, 2.9793534e-01, 1.1570342e-02, 4.5793110e-01,
       4.3596479e-01, 1.1353558e-01, 3.6170322e-01, 4.4363216e-02,
       7.2716069e-01, 1.9414751e-01, 8.9970458e-01, 5.6418572e-02,
       6.5900785e-01, 2.7703318e-01, 2.4434039e-01, 4.6711516e-02,
       7.1524179e-01, 7.6018190e-01, 9.5102049e-02, 4.7169948e-01,
       5.6472950e-02, 6.1109054e-01, 9.3535668e-01, 4.7199135e-03,
       6.3798469e-01, 4.3597910e-01, 3.4474665e-01, 2.7098738e-02,
       5.4479504e-01, 1.0274617e-01], dtype=float32)>

In [94]:
# sqrt from documentation (F3) (and compare to F2, F3):
F2, F3, tf.math.sqrt(F3)

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, <tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([4.4164279e-01, 1.9448698e-01, 1.2452606e-01, 2.1574403e-01,
        1.1330233e-03, 4.6877623e-01, 5.4777384e-01, 7.6115942e-01,
        5.1223613e-02, 4.9816839e-02, 9.6340768e-02, 5.2176905e-

In [95]:
# video example
# create a new tensor

H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [96]:
# square 
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [97]:
# sqrt
tf.sqrt(tf.cast(H, dtype=tf.float32)) # this was my test, I assume convert to float, but output is a little different to video 26 (3.43.44)

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [98]:
# log
tf.math.log(tf.cast(H, dtype=tf.float32)) # seems to need a float, this is my guess before seeing video

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [99]:
# video 27

### Tnesors and NumPy

what is NumPy - fundamental package for scientific computing using python

TensorFlow interacts beautifully with NumPy Arrays 

In [100]:
# create a tensor directly from a Numpy array 

J = tf.constant(np.array([3., 7., 10.]))
J


<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [101]:
# convert it back from Tensor to NumPy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [102]:
# convert Tensor J to a NumPy Array using 

J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [103]:
# the default types of each are slightly different as can be seen below
# this is important because you may be expecting different datatypes than what you get.....

numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

#check the datatypes of each:
numpy_J.dtype, tensor_J.dtype


(tf.float64, tf.float32)